export const FETCH_ALL_COUNTRIES_START = 'FETCH_ALL_COUNTRIES_START';
export const FETCH_ALL_COUNTRIES_SUCCESS = 'FETCH_ALL_COUNTRIES_SUCCESS';
export const FETCH_ALL_COUNTRIES_ERROR = 'FETCH_ALL_COUNTRIES_ERROR';

export const FETCH_ONE_COUNTRY_START = 'FETCH_ONE_COUNTRY_START';
export const FETCH_ONE_COUNTRY_SUCCESS = 'FETCH_ONE_COUNTRY_SUCCESS';
export const FETCH_ONE_COUNTRY_ERROR = 'FETCH_ONE_COUNTRY_ERROR';
